"use client"; // client side rendering

import React, { useRef } from "react";

import { Color, Group, Mesh } from "three";
import { MeshTransmissionMaterial } from "@react-three/drei";

const Planet = () => {
  const meshRef = useRef<Mesh>(null!);

  return (
    <mesh ref={meshRef} scale={0.3}>
      <sphereGeometry />
      <meshStandardMaterial />
    </mesh>
  );
};

/* Auto-generated by: https://github.com/pmndrs/gltfjsx */
const Dome = () => {
  // TODO : need to remove error on nodes.Dome.geometry (typescript lint)
  // NOTE : is not implemented in this version but is a refering to GLTF file loading
  return (
    <group dispose={null}>
      <mesh castShadow>
        <boxGeometry />
        <MeshTransmissionMaterial
          backside
          backsideThickness={-1}
          thickness={0.2}
          anisotropicBlur={0.02}
          chromaticAberration={0.5}
          distortion={0.05}
          distortionScale={0.07}
          temporalDistortion={0.1}
          transmission={1}
          color="#a1c6ff"
          attenuationColor="#ffffff"
          background={new Color("#839681")}
        />
      </mesh>
    </group>
  );
};

export const Avatar = () => {
  const groupRef = useRef<Group>(null!);

  // useFrame(({ pointer, viewport }) => {
  //   const x = (pointer.x * viewport.width) / 2.5;
  //   const y = (pointer.y * viewport.height) / 2.5;
  //   groupRef.current.lookAt(x, y, 1);
  // });

  return (
    <group ref={groupRef} dispose={null}>
      <Dome />
      <Planet />
    </group>
  );
};
