import React from "react";
import { useInstances } from "../utils/landing/GLTFLoadingUtils";

/**
 * Computer Component
 *
 * This component represents a 3D computer model, leveraging instances and materials
 * loaded using the `useInstances` utility.
 *
 * @see GLTFLoadingUtils
 *
 * Based on code generated by: https://github.com/pmndrs/gltfjsx
 *
 * @param {JSX.IntrinsicElements["group"]} props - Props passed to the parent group
 * for positioning, rotation, or scaling within the scene.
 */
export function Computer(props: JSX.IntrinsicElements["group"]) {
  const { instances, materials } = useInstances();

  return (
    <group {...props}>
      <instances.computerBase
        material={materials["Material.001"]}
        position={[-0.5, 1, 0.5]}
      />
      <instances.computerScreen
        material={materials["Material.000"]}
        position={[-0.449, 3.798, 0.899]}
        scale={0.899}
      />
    </group>
  );
}
