/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from "react";
import { useInstances } from "../utils/landing/GLTFLoadingUtils";

// TODO : [blender/three] fix the fact that the model is turned around
// TODO : [blender] simplify the model
// TODO : does not work ...
export function Computer(props: JSX.IntrinsicElements["group"]) {
  const { instances, materials } = useInstances();

  return (
    <group {...props}>
      <instances.computerBase
        material={materials["Material.001"]}
        position={[-0.5, 1, 0.5]}
      />
      <instances.computerScreen
        material={materials["Material.000"]}
        position={[-0.449, 3.798, 0.899]}
        scale={0.899}
      />
    </group>
  );
}
